- name: categories
  lines: 20
  freq: 10
  columns:
    - name: id
      type: INTEGER
    - name: name
      type: TEXT
- name: manufacturers
  lines: 30
  columns:
    - name: id
      type: INTEGER
    - name: name
      type: TEXT
    - name: country
      type: TEXT
- name: products
  lines: 100
  freq: 5
  columns:
    - name: id
      type: INTEGER
    - name: name
      type: TEXT
    - name: category_id
      type: INTEGER
    - name: manufacturer_id
      type: INTEGER
    - name: price
      type: REAL
- name: price_change
  lines: 150
  freq: 8
  columns:
    - name: id
      type: INTEGER
    - name: product_id
      type: INTEGER
    - name: price
      type: REAL
    - name: change_date
      type: DATE
- name: stores
  lines: 20
  freq: 4
  colunms:
    - name: id
      type: INTEGER
    - name: name
      type: TEXT
    - name: address
      type: TEXT
- name: deliveries
  lines: 100
  freq: 15
  columns:
    - name: id
      type: INTEGER
    - name: product_id
      type: INTEGER
    - name: store_id
      type: INTEGER
    - name: quantity
      type: INTEGER
    - name: delivery_date
      type: DATE
- name: customers
  lines: 50
  freq: 20
  columns:
    - name: id
      type: INTEGER
    - name: full_name
      type: TEXT
    - name: phone
      type: TEXT
    - name: email
      type: TEXT
    - name: registration_date
      type: DATE
- name: purchases
  lines: 100
  freq: 6
  columns:
    - name: id
      type: INTEGER
    - name: customer_id
      type: INTEGER
    - name: purchase_date
      type: DATE
- name: purchase_items
  lines: 150
  freq: 8
  columns:
    - name: id
      type: INTEGER
    - name: purchase_id
      type: INTEGER
    - name: product_id
      type: INTEGER
    - name: quantity
      type: INTEGER
